# Generated by Django 5.1.4 on 2024-12-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=255)),
                ('Price', models.IntegerField()),
                ('Description', models.CharField(max_length=255)),
                ('Edition', models.CharField(max_length=255)),
                ('Publisher', models.CharField(max_length=255)),
                ('Published', models.CharField(max_length=255)),
                ('Language', models.CharField(max_length=255)),
                ('Pages', models.IntegerField()),
                ('Image', models.ImageField(upload_to='upload/')),
            ],
            options={
                'db_table': 'Book_Details',
            },
        ),
    ]
