# Generated by Django 5.1.4 on 2025-01-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Published',
            field=models.DateField(),
        ),
    ]
