# Generated by Django 5.1.4 on 2025-01-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Email',
            field=models.EmailField(max_length=255),
        ),
    ]
