# Generated by Django 5.1.4 on 2025-01-15 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_alter_register_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.book')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.register')),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
    ]
