# Generated by Django 5.1.4 on 2025-01-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0007_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='heart_on',
            field=models.BooleanField(default=False),
        ),
    ]
