# Generated by Django 5.1.4 on 2025-01-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0008_book_heart_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='heart_on',
            field=models.BooleanField(default=False),
        ),
    ]
