# Generated by Django 5.1.4 on 2025-01-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0010_remove_book_heart_on_remove_wishlist_heart_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Heart',
            field=models.BooleanField(default=False),
        ),
    ]
