# Generated by Django 5.1.4 on 2025-01-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0011_book_heart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('Bill_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Bill_Name', models.CharField(max_length=255)),
                ('Bill_Email', models.EmailField(max_length=255)),
                ('Bill_Number', models.CharField(max_length=12)),
                ('Bill_Address', models.TextField()),
                ('Bill_City', models.CharField(max_length=255)),
                ('Bill_ZipCode', models.CharField(max_length=8)),
                ('Bill_Quantity', models.IntegerField()),
                ('Bill_Price', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Billing_Details',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Pay_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Card_Name', models.CharField(max_length=255)),
                ('Card_Number', models.CharField(max_length=255)),
                ('Card_Month', models.CharField(max_length=20)),
                ('Card_Year', models.CharField(max_length=10)),
                ('Card_Cvv', models.IntegerField()),
                ('Price', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Payment_Details',
            },
        ),
    ]
