# Generated by Django 5.1.4 on 2025-01-22 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0012_billing_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='Book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Book.book'),
        ),
        migrations.AddField(
            model_name='billing',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Book.register'),
        ),
        migrations.AddField(
            model_name='payment',
            name='Book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Book.book'),
        ),
        migrations.AddField(
            model_name='payment',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Book.register'),
        ),
    ]
