# Generated by Django 5.1.4 on 2025-01-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0013_billing_book_billing_user_payment_book_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='Bill_Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
