# Generated by Django 5.1.4 on 2025-01-23 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0014_alter_billing_bill_price_alter_payment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='Book',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='User',
        ),
        migrations.AddField(
            model_name='billing',
            name='Pay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Book.payment'),
        ),
    ]
