# Generated by Django 5.1.4 on 2025-01-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0015_remove_billing_book_remove_billing_user_billing_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Price',
        ),
    ]
