# Generated by Django 5.1.4 on 2025-01-30 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0017_remove_billing_pay_billing_book_billing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Book.register'),
        ),
        migrations.AddField(
            model_name='register',
            name='Category',
            field=models.IntegerField(default=1),
        ),
    ]
